# Generated by Django 5.0 on 2025-08-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название компании"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(upload_to="partners/", verbose_name="Логотип"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Поставщик"),
                            ("client", "Клиент"),
                            ("distributor", "Дистрибьютор"),
                            ("service", "Сервисный партнер"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип партнерства",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание сотрудничества"),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала сотрудничества"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания сотрудничества",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partners.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнерство",
                "verbose_name_plural": "Партнерства",
                "ordering": ["-start_date"],
            },
        ),
    ]
